# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_med.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 1266)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.profile = QtWidgets.QFrame(self.centralwidget)
        self.profile.setGeometry(QtCore.QRect(790, 0, 91, 41))
        self.profile.setStyleSheet("QFrame{\n"
"border: none;\n"
"border-radius: 5px\n"
"}")
        self.profile.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.profile.setObjectName("profile")
        self.profile_btn_3 = QtWidgets.QPushButton(self.profile)
        self.profile_btn_3.setGeometry(QtCore.QRect(0, 0, 91, 41))
        self.profile_btn_3.setStyleSheet("QPushButton{\n"
"    background-color: white;\n"
"    font: 500 15pt \"Epilogue\";\n"
"    color:#1D1D1D;\n"
"    border-radius: 10px;\n"
"    border-color: none\n"
"}\n"
"QPushButton:checked {\n"
"    background-color:    #EFEFEF;\n"
"}")
        self.profile_btn_3.setCheckable(True)
        self.profile_btn_3.setObjectName("profile_btn_3")
        self.exercise = QtWidgets.QFrame(self.centralwidget)
        self.exercise.setGeometry(QtCore.QRect(570, 0, 91, 41))
        self.exercise.setStyleSheet("QFrame{\n"
"border: none;\n"
"border-radius: 5px\n"
"}")
        self.exercise.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.exercise.setObjectName("exercise")
        self.exercise_btn_3 = QtWidgets.QPushButton(self.exercise)
        self.exercise_btn_3.setGeometry(QtCore.QRect(0, 0, 91, 41))
        self.exercise_btn_3.setStyleSheet("QPushButton{\n"
"    background-color: white;\n"
"    font: 500 15pt \"Epilogue\";\n"
"    color:#1D1D1D;\n"
"    border-radius: 10px;\n"
"    border-color: none\n"
"}\n"
"QPushButton:checked {\n"
"    background-color:    #EFEFEF;\n"
"}")
        self.exercise_btn_3.setCheckable(True)
        self.exercise_btn_3.setObjectName("exercise_btn_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 0, 131, 51))
        self.label.setStyleSheet("QLabel{\n"
"background-color: none;\n"
"font: 800 25px \"Epilogue\";\n"
"color: #1D1D1D\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 50, 831, 2))
        self.line.setStyleSheet("#line{\n"
"    height:1px;\n"
"    background-color: #e8e8e8;\n"
"    border:none;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.dashboard = QtWidgets.QFrame(self.centralwidget)
        self.dashboard.setGeometry(QtCore.QRect(340, 0, 131, 41))
        self.dashboard.setStyleSheet("QFrame{\n"
"border: none;\n"
"border-radius: 5px\n"
"}")
        self.dashboard.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dashboard.setObjectName("dashboard")
        self.dashboard_btn_3 = QtWidgets.QPushButton(self.dashboard)
        self.dashboard_btn_3.setGeometry(QtCore.QRect(20, 0, 111, 41))
        self.dashboard_btn_3.setStyleSheet("QPushButton{\n"
"    background-color: white;\n"
"    font: 500 15pt \"Epilogue\";\n"
"    color:#1D1D1D;\n"
"    border-radius: 10px;\n"
"    border-color: none\n"
"}\n"
"QPushButton:checked {\n"
"    background-color:    #EFEFEF;\n"
"}")
        self.dashboard_btn_3.setCheckable(True)
        self.dashboard_btn_3.setObjectName("dashboard_btn_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 60, 911, 1111))
        self.tabWidget.setStyleSheet("QTabWidget{\n"
"background-color: none;\n"
"height: 0px;\n"
"width: 0px;\n"
"padding: 0px;\n"
"margin: 0px;\n"
"border: 0px\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_11)
        self.scrollArea_3.setGeometry(QtCore.QRect(-20, 0, 931, 1121))
        self.scrollArea_3.setStyleSheet("QScrollArea{\n"
"    background-color: white;\n"
"    border:0px solid white\n"
"}")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scroll_contents_3 = QtWidgets.QWidget()
        self.scroll_contents_3.setGeometry(QtCore.QRect(0, 0, 931, 1121))
        self.scroll_contents_3.setObjectName("scroll_contents_3")
        self.prog_lbl_3 = QtWidgets.QLabel(self.scroll_contents_3)
        self.prog_lbl_3.setGeometry(QtCore.QRect(270, 0, 401, 71))
        self.prog_lbl_3.setStyleSheet("QLabel{\n"
"    background-color: white;\n"
"    color: #1D1D1D;\n"
"    font: 500 35pt \"Epilogue\";\n"
"}")
        self.prog_lbl_3.setObjectName("prog_lbl_3")
        self.day_lbl_3 = QtWidgets.QLabel(self.scroll_contents_3)
        self.day_lbl_3.setGeometry(QtCore.QRect(280, 70, 351, 21))
        self.day_lbl_3.setStyleSheet("QLabel{\n"
"    background-color: white;\n"
"    color: #939393;\n"
"    font: 15pt \"Epilogue\";\n"
"}")
        self.day_lbl_3.setText("")
        self.day_lbl_3.setObjectName("day_lbl_3")
        self.cal_3 = QtWidgets.QLabel(self.scroll_contents_3)
        self.cal_3.setGeometry(QtCore.QRect(80, 110, 351, 211))
        self.cal_3.setStyleSheet("QLabel{\n"
"background-color:white;\n"
"border: 1px solid #C0C0C0;\n"
"border-radius:10px;\n"
"font:15px \"Epilogue\";\n"
"color:#C0C0C0;\n"
"padding-bottom:90;\n"
"padding-left:137\n"
"}")
        self.cal_3.setObjectName("cal_3")
        self.prot_3 = QtWidgets.QLabel(self.scroll_contents_3)
        self.prot_3.setGeometry(QtCore.QRect(490, 110, 351, 211))
        self.prot_3.setStyleSheet("QLabel{\n"
"background-color:white;\n"
"border: 1px solid #C0C0C0;\n"
"border-radius:10px;\n"
"font:15px \"Epilogue\";\n"
"color:#C0C0C0;\n"
"padding-bottom:90;\n"
"padding-left:142\n"
"}")
        self.prot_3.setObjectName("prot_3")
        self.fat_3 = QtWidgets.QLabel(self.scroll_contents_3)
        self.fat_3.setGeometry(QtCore.QRect(490, 340, 351, 211))
        self.fat_3.setStyleSheet("QLabel{\n"
"background-color:white;\n"
"border: 1px solid #C0C0C0;\n"
"border-radius:10px;\n"
"font:15px \"Epilogue\";\n"
"color:#C0C0C0;\n"
"padding-bottom:90;\n"
"padding-left:162\n"
"}")
        self.fat_3.setObjectName("fat_3")
        self.carb_3 = QtWidgets.QLabel(self.scroll_contents_3)
        self.carb_3.setGeometry(QtCore.QRect(80, 340, 351, 211))
        self.carb_3.setStyleSheet("QLabel{\n"
"background-color:white;\n"
"border: 1px solid #C0C0C0;\n"
"border-radius:10px;\n"
"font:15px \"Epilogue\";\n"
"color:#C0C0C0;\n"
"padding-bottom:90;\n"
"padding-left:142\n"
"}")
        self.carb_3.setObjectName("carb_3")
        self.cal_counter_3 = QtWidgets.QLabel(self.scroll_contents_3)
        self.cal_counter_3.setGeometry(QtCore.QRect(140, 180, 231, 91))
        self.cal_counter_3.setStyleSheet("QLabel{\n"
"    font: 700 40pt \"Epilogue\";\n"
"    color:#1D1D1D\n"
"}")
        self.cal_counter_3.setText("")
        self.cal_counter_3.setObjectName("cal_counter_3")
        self.prot_counter_3 = QtWidgets.QLabel(self.scroll_contents_3)
        self.prot_counter_3.setGeometry(QtCore.QRect(540, 180, 261, 91))
        self.prot_counter_3.setStyleSheet("QLabel{\n"
"    font: 700 40pt \"Epilogue\";\n"
"    color:#1D1D1D\n"
"}")
        self.prot_counter_3.setText("")
        self.prot_counter_3.setObjectName("prot_counter_3")
        self.carbs_counter_3 = QtWidgets.QLabel(self.scroll_contents_3)
        self.carbs_counter_3.setGeometry(QtCore.QRect(120, 420, 261, 91))
        self.carbs_counter_3.setStyleSheet("QLabel{\n"
"    font: 700 40pt \"Epilogue\";\n"
"    color:#1D1D1D\n"
"}")
        self.carbs_counter_3.setText("")
        self.carbs_counter_3.setObjectName("carbs_counter_3")
        self.fats_counter_3 = QtWidgets.QLabel(self.scroll_contents_3)
        self.fats_counter_3.setGeometry(QtCore.QRect(540, 420, 251, 91))
        self.fats_counter_3.setStyleSheet("QLabel{\n"
"    font: 700 40pt \"Epilogue\";\n"
"    color:#1D1D1D\n"
"}")
        self.fats_counter_3.setText("")
        self.fats_counter_3.setObjectName("fats_counter_3")
        self.scan_btn_3 = QtWidgets.QPushButton(self.scroll_contents_3)
        self.scan_btn_3.setGeometry(QtCore.QRect(80, 920, 761, 61))
        self.scan_btn_3.setStyleSheet("QPushButton{\n"
"    background-color:#1D1D1D;\n"
"    font: 600 25pt \"Epilogue\";\n"
"    border-radius:25px;\n"
"    color:white;\n"
"    padding-bottom:7px\n"
"}\n"
"")
        self.scan_btn_3.setObjectName("scan_btn_3")
        self.recipe_t_3 = QtWidgets.QPushButton(self.scroll_contents_3)
        self.recipe_t_3.setGeometry(QtCore.QRect(80, 1000, 761, 61))
        self.recipe_t_3.setStyleSheet("QPushButton{\n"
"    background-color:white;\n"
"    font: 600 25pt \"Epilogue\";\n"
"    border-radius:25px;\n"
"    color: #1D1D1D;\n"
"    border:1px solid #C0C0C0\n"
"}")
        self.recipe_t_3.setObjectName("recipe_t_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.scroll_contents_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(80, 570, 761, 331))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.meal_log_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.meal_log_3.setContentsMargins(0, 0, 0, 0)
        self.meal_log_3.setObjectName("meal_log_3")
        self.meal_log_widget_3 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self.meal_log_widget_3.setStyleSheet("QWidget{\n"
"font: 400 20px \"Epilogue\";\n"
"color:#1d1d1d;\n"
"border-radius:10px;\n"
"background-color:rgb(242, 242, 242);\n"
"border:1px solid #c0c0c0\n"
"}")
        self.meal_log_widget_3.setObjectName("meal_log_widget_3")
        self.label_4 = QtWidgets.QLabel(self.meal_log_widget_3)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 171, 51))
        self.label_4.setStyleSheet("QLabel{\n"
"font: 300 25px \"Epilogue\";\n"
"color:#1d1d1d;\n"
"background-color:#f2f2f2;\n"
"border:none;\n"
"\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.meal_log_3.addWidget(self.meal_log_widget_3)
        self.scrollArea_3.setWidget(self.scroll_contents_3)
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.widget_3 = QtWidgets.QWidget(self.tab_12)
        self.widget_3.setGeometry(QtCore.QRect(30, 0, 821, 821))
        self.widget_3.setStyleSheet("QWidget{\n"
"    border:1px solid #C0C0C0;\n"
"    border-radius: 10px\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.search_bar_3 = QtWidgets.QLineEdit(self.widget_3)
        self.search_bar_3.setGeometry(QtCore.QRect(30, 30, 761, 51))
        self.search_bar_3.setStyleSheet("QLineEdit{\n"
"    color:#C0C0C0;\n"
"    font: 300 13pt \"Epilogue\";\n"
"    padding-left:5px\n"
"}\n"
"")
        self.search_bar_3.setObjectName("search_bar_3")
        self.igr_select_3 = QtWidgets.QLabel(self.widget_3)
        self.igr_select_3.setGeometry(QtCore.QRect(30, 90, 241, 41))
        self.igr_select_3.setStyleSheet("QLabel{\n"
"    font: 300 20pt \"Epilogue\";\n"
"    color:#1D1D1D;\n"
"    border:none;\n"
"}")
        self.igr_select_3.setObjectName("igr_select_3")
        self.ingr_add_3 = QtWidgets.QWidget(self.widget_3)
        self.ingr_add_3.setGeometry(QtCore.QRect(10, 130, 801, 421))
        self.ingr_add_3.setStyleSheet("QWidget{\n"
"    border:none;\n"
"}")
        self.ingr_add_3.setObjectName("ingr_add_3")
        self.save_recipe_btn_3 = QtWidgets.QPushButton(self.widget_3)
        self.save_recipe_btn_3.setGeometry(QtCore.QRect(70, 660, 671, 51))
        self.save_recipe_btn_3.setStyleSheet("QPushButton{\n"
"    background-color:#1D1D1D;\n"
"    font: 500 20px \"Epilogue\";\n"
"    border-radius: 25px;\n"
"\n"
"}")
        self.save_recipe_btn_3.setObjectName("save_recipe_btn_3")
        self.new_recipe_btn_3 = QtWidgets.QPushButton(self.widget_3)
        self.new_recipe_btn_3.setGeometry(QtCore.QRect(70, 580, 671, 51))
        self.new_recipe_btn_3.setStyleSheet("QPushButton{\n"
"    background-color:#1D1D1D;\n"
"    font: 500 20px \"Epilogue\";\n"
"    border-radius: 25px;\n"
"\n"
"}")
        self.new_recipe_btn_3.setObjectName("new_recipe_btn_3")
        self.tabWidget.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.tabWidget.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.prog_lbl_4 = QtWidgets.QLabel(self.tab_14)
        self.prog_lbl_4.setGeometry(QtCore.QRect(347, 0, 191, 71))
        self.prog_lbl_4.setStyleSheet("QLabel{\n"
"    background-color: white;\n"
"    color: #1D1D1D;\n"
"    font: 500 35pt \"Epilogue\";\n"
"}")
        self.prog_lbl_4.setAlignment(QtCore.Qt.AlignCenter)
        self.prog_lbl_4.setObjectName("prog_lbl_4")
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab_14)
        self.spinBox_2.setGeometry(QtCore.QRect(510, 110, 111, 41))
        self.spinBox_2.setStyleSheet("QSpinBox {\n"
"    font-family: Epilogue;  \n"
"    font-size: 20pt;\n"
"    background-color: rgb(255,255,255);\n"
"    border-radius:10 pt;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QSpinBox:QLineEdit {\n"
"    background-color: rgb(255,255,255);\n"
"    border: none;\n"
"    padding: 4px 6px;\n"
"}")
        self.spinBox_2.setProperty("value", 4)
        self.spinBox_2.setObjectName("spinBox_2")
        self.prog_lbl_5 = QtWidgets.QLabel(self.tab_14)
        self.prog_lbl_5.setGeometry(QtCore.QRect(120, 180, 651, 41))
        self.prog_lbl_5.setStyleSheet("QLabel{\n"
"    background-color: white;\n"
"    color: #1D1D1D;\n"
"    font: 500 14pt \"Epilogue\";\n"
"}")
        self.prog_lbl_5.setAlignment(QtCore.Qt.AlignCenter)
        self.prog_lbl_5.setObjectName("prog_lbl_5")
        self.prog_lbl_6 = QtWidgets.QLabel(self.tab_14)
        self.prog_lbl_6.setGeometry(QtCore.QRect(220, 110, 231, 41))
        self.prog_lbl_6.setStyleSheet("QLabel{\n"
"    background-color: white;\n"
"    color: #1D1D1D;\n"
"    font: 500 14pt \"Epilogue\";\n"
"}")
        self.prog_lbl_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prog_lbl_6.setObjectName("prog_lbl_6")
        self.scan_btn_4 = QtWidgets.QPushButton(self.tab_14)
        self.scan_btn_4.setGeometry(QtCore.QRect(300, 260, 281, 61))
        self.scan_btn_4.setStyleSheet("QPushButton{\n"
"    background-color:#1D1D1D;\n"
"    font: 600 25pt \"Epilogue\";\n"
"    border-radius:25px;\n"
"    color:white;\n"
"    padding-bottom:7px\n"
"}\n"
"")
        self.scan_btn_4.setObjectName("scan_btn_4")
        self.label_7 = QtWidgets.QLabel(self.tab_14)
        self.label_7.setGeometry(QtCore.QRect(20, 80, 841, 681))
        self.label_7.setStyleSheet("QLabel{\n"
"    border: 1px solid #D4D4D4;\n"
"    border-radius:5px;\n"
"    background-color: #F9F9F9\n"
"}")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab_14)
        self.graphicsView.setGeometry(QtCore.QRect(290, 240, 300, 300))
        self.graphicsView.setStyleSheet("background-color: qradialgradient(\n"
"        spread: pad, \n"
"        cx: 0.5, cy: 0.5,    \n"
"         radius: 0.8,          \n"
"         fx: 0.5, fy: 0.5,   \n"
"         stop: 0    #FFD5D5, \n"
"         stop: 0.26 #FFB5B5, \n"
"         stop: 1    #FFD5F6   \n"
"    );\n"
"border: 0px;\n"
"border-radius: 150px;   \n"
"")
        self.graphicsView.setObjectName("graphicsView")
        self.prog_lbl_7 = QtWidgets.QLabel(self.tab_14)
        self.prog_lbl_7.setGeometry(QtCore.QRect(350, 130, 191, 71))
        self.prog_lbl_7.setStyleSheet("QLabel{\n"
"    background-color: white;\n"
"    color: #1D1D1D;\n"
"    font: 500 20pt \"Epilogue\";\n"
"}")
        self.prog_lbl_7.setAlignment(QtCore.Qt.AlignCenter)
        self.prog_lbl_7.setObjectName("prog_lbl_7")
        self.prog_lbl_5.raise_()
        self.prog_lbl_4.raise_()
        self.spinBox_2.raise_()
        self.prog_lbl_6.raise_()
        self.scan_btn_4.raise_()
        self.label_7.raise_()
        self.graphicsView.raise_()
        self.prog_lbl_7.raise_()
        self.tabWidget.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.widget_5 = QtWidgets.QWidget(self.tab_15)
        self.widget_5.setGeometry(QtCore.QRect(0, 0, 881, 721))
        self.widget_5.setStyleSheet("QWidget{\n"
"background-color:white\n"
"}")
        self.widget_5.setObjectName("widget_5")
        self.label_6 = QtWidgets.QLabel(self.widget_5)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 841, 681))
        self.label_6.setStyleSheet("QLabel{\n"
"    border: 1px solid #D4D4D4;\n"
"    border-radius:5px;\n"
"    background-color: #F9F9F9\n"
"}")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.heading_3 = QtWidgets.QLabel(self.widget_5)
        self.heading_3.setGeometry(QtCore.QRect(40, 40, 231, 31))
        self.heading_3.setStyleSheet("QLabel{\n"
"    background-color:#F9F9F9;\n"
"    font: 200 22pt \"Epilogue\";\n"
"    color: #1D1D1D\n"
"\n"
"}\n"
"")
        self.heading_3.setObjectName("heading_3")
        self.name_3 = QtWidgets.QLabel(self.widget_5)
        self.name_3.setGeometry(QtCore.QRect(40, 100, 61, 31))
        self.name_3.setStyleSheet("QLabel{\n"
"    background-color:#F9F9F9;\n"
"    font: 200 15pt \"Epilogue\";\n"
"    color: #1D1D1D\n"
"\n"
"}\n"
"")
        self.name_3.setObjectName("name_3")
        self.line_name_3 = QtWidgets.QLineEdit(self.widget_5)
        self.line_name_3.setGeometry(QtCore.QRect(40, 130, 791, 31))
        self.line_name_3.setStyleSheet("QLineEdit{\n"
"background-color: white;\n"
"border-radius: 5px;\n"
"border: 1px solid #D7D7D7;\n"
"font: 200 15px \"Epilogue\";\n"
"color: #1D1D1D\n"
"}")
        self.line_name_3.setObjectName("line_name_3")
        self.age_3 = QtWidgets.QLabel(self.widget_5)
        self.age_3.setGeometry(QtCore.QRect(40, 180, 41, 31))
        self.age_3.setStyleSheet("QLabel{\n"
"    background-color:#F9F9F9;\n"
"    font: 200 15pt \"Epilogue\";\n"
"    color: #1D1D1D\n"
"\n"
"}\n"
"")
        self.age_3.setObjectName("age_3")
        self.line_age_3 = QtWidgets.QLineEdit(self.widget_5)
        self.line_age_3.setGeometry(QtCore.QRect(40, 220, 351, 31))
        self.line_age_3.setStyleSheet("QLineEdit{\n"
"background-color: white;\n"
"border-radius: 5px;\n"
"border: 1px solid #D7D7D7;\n"
"color: #1D1D1D\n"
"}")
        self.line_age_3.setObjectName("line_age_3")
        self.gender_3 = QtWidgets.QLabel(self.widget_5)
        self.gender_3.setGeometry(QtCore.QRect(470, 180, 71, 31))
        self.gender_3.setStyleSheet("QLabel{\n"
"    background-color:#F9F9F9;\n"
"    font: 200 15pt \"Epilogue\";\n"
"    color: #1D1D1D\n"
"\n"
"}\n"
"")
        self.gender_3.setObjectName("gender_3")
        self.line_gender_3 = QtWidgets.QComboBox(self.widget_5)
        self.line_gender_3.setGeometry(QtCore.QRect(470, 210, 361, 31))
        self.line_gender_3.setStyleSheet("QComboBox{\n"
"background-color: white;\n"
"border-radius: 5px;\n"
"border: 1px solid #D7d7d7;\n"
"color: #1D1D1D;\n"
"font: 300 10px \"Epilogue\";\n"
"padding-left:5px\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"     background-color: white;\n"
"     border: 1px solid #D7D7D7;\n"
"     selection-background-color: #eee;\n"
"     selection-color: black;\n"
"     outline: none;\n"
"     border-radius: 0px;\n"
"    color: #1D1D1D;\n"
"    height: 30px;\n"
"    padding-left:5px;\n"
"    border: 1px solid #D7D7D7; \n"
"    outline: none;\n"
"}\n"
"QComboBox QAbstractItemView :: viewport{\n"
"    border: none;\n"
"    background-color: transparent\n"
"}")
        self.line_gender_3.setObjectName("line_gender_3")
        self.line_gender_3.addItem("")
        self.line_gender_3.addItem("")
        self.line_gender_3.addItem("")
        self.height_3 = QtWidgets.QLabel(self.widget_5)
        self.height_3.setGeometry(QtCore.QRect(40, 270, 111, 31))
        self.height_3.setStyleSheet("QLabel{\n"
"    background-color:#F9F9F9;\n"
"    font: 200 15pt \"Epilogue\";\n"
"    color: #1D1D1D\n"
"\n"
"}\n"
"")
        self.height_3.setObjectName("height_3")
        self.line_height_3 = QtWidgets.QLineEdit(self.widget_5)
        self.line_height_3.setGeometry(QtCore.QRect(40, 310, 351, 31))
        self.line_height_3.setStyleSheet("QLineEdit{\n"
"background-color: white;\n"
"border-radius: 5px;\n"
"border: 1px solid #D7D7D7;\n"
"color:#1D1D1D\n"
"}")
        self.line_height_3.setObjectName("line_height_3")
        self.weight_3 = QtWidgets.QLabel(self.widget_5)
        self.weight_3.setGeometry(QtCore.QRect(470, 270, 111, 31))
        self.weight_3.setStyleSheet("QLabel{\n"
"    background-color:#F9F9F9;\n"
"    font: 200 15pt \"Epilogue\";\n"
"    color: #1D1D1D\n"
"\n"
"}\n"
"")
        self.weight_3.setObjectName("weight_3")
        self.line_weight_3 = QtWidgets.QLineEdit(self.widget_5)
        self.line_weight_3.setGeometry(QtCore.QRect(460, 310, 371, 31))
        self.line_weight_3.setStyleSheet("QLineEdit{\n"
"background-color: white;\n"
"border-radius: 5px;\n"
"border: 1px solid #D7D7D7;\n"
"color:#1D1D1D\n"
"}")
        self.line_weight_3.setObjectName("line_weight_3")
        self.goal_weight_3 = QtWidgets.QLabel(self.widget_5)
        self.goal_weight_3.setGeometry(QtCore.QRect(40, 370, 121, 31))
        self.goal_weight_3.setStyleSheet("QLabel{\n"
"    background-color:#F9F9F9;\n"
"    font: 200 15pt \"Epilogue\";\n"
"    color: #1D1D1D\n"
"\n"
"}\n"
"")
        self.goal_weight_3.setObjectName("goal_weight_3")
        self.line_goal_3 = QtWidgets.QLineEdit(self.widget_5)
        self.line_goal_3.setGeometry(QtCore.QRect(40, 410, 791, 31))
        self.line_goal_3.setStyleSheet("QLineEdit{\n"
"background-color: white;\n"
"border-radius: 5px;\n"
"border: 1px solid #D7D7D7;\n"
"color:#1D1D1D\n"
"}")
        self.line_goal_3.setObjectName("line_goal_3")
        self.diet_pref_3 = QtWidgets.QLabel(self.widget_5)
        self.diet_pref_3.setGeometry(QtCore.QRect(40, 460, 231, 31))
        self.diet_pref_3.setStyleSheet("QLabel{\n"
"    background-color:#F9F9F9;\n"
"    font: 200 15pt \"Epilogue\";\n"
"    color: #1D1D1D\n"
"\n"
"}\n"
"")
        self.diet_pref_3.setObjectName("diet_pref_3")
        self.line_diet_3 = QtWidgets.QComboBox(self.widget_5)
        self.line_diet_3.setGeometry(QtCore.QRect(40, 520, 791, 31))
        self.line_diet_3.setStyleSheet("QComboBox{\n"
"background-color: white;\n"
"border-radius: 5px;\n"
"border: 1px solid #D7D7D7;\n"
"color: #1D1D1D;\n"
"font:300 10px \"Epilogue\";\n"
"padding-left:5px\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"     background-color: white;\n"
"     border: 1px solid #D7D7D7;\n"
"    outline: none;\n"
"     selection-background-color: #eee;\n"
"     selection-color: black;\n"
"     outline: none;\n"
"     border-radius: 0px; \n"
"    color: #1D1D1D;\n"
"    height: 35px;\n"
"    padding-left:5px\n"
"\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"QComboBox QAbstractItemView :: viewport{\n"
"    border: none;\n"
"    background-color: transparent\n"
"}")
        self.line_diet_3.setObjectName("line_diet_3")
        self.line_diet_3.addItem("")
        self.line_diet_3.addItem("")
        self.tabWidget.addTab(self.tab_15, "")
        self.meditation = QtWidgets.QFrame(self.centralwidget)
        self.meditation.setGeometry(QtCore.QRect(670, 0, 111, 41))
        self.meditation.setStyleSheet("QFrame{\n"
"border: none;\n"
"border-radius: 5px\n"
"}")
        self.meditation.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.meditation.setObjectName("meditation")
        self.mediation_btn_3 = QtWidgets.QPushButton(self.meditation)
        self.mediation_btn_3.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.mediation_btn_3.setStyleSheet("QPushButton{\n"
"    background-color: white;\n"
"    font: 500 15pt \"Epilogue\";\n"
"    color:#1D1D1D;\n"
"    border-radius: 10px;\n"
"    border-color: none\n"
"}\n"
"QPushButton:checked {\n"
"    background-color:    #EFEFEF;\n"
"}")
        self.mediation_btn_3.setCheckable(True)
        self.mediation_btn_3.setObjectName("mediation_btn_3")
        self.recipe = QtWidgets.QFrame(self.centralwidget)
        self.recipe.setGeometry(QtCore.QRect(480, 0, 91, 41))
        self.recipe.setStyleSheet("QFrame{\n"
"border: none;\n"
"border-radius: 5px\n"
"}")
        self.recipe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.recipe.setObjectName("recipe")
        self.recipe_btn_3 = QtWidgets.QPushButton(self.recipe)
        self.recipe_btn_3.setGeometry(QtCore.QRect(0, 0, 81, 41))
        self.recipe_btn_3.setStyleSheet("QPushButton{\n"
"    background-color: white;\n"
"    font: 500 15pt \"Epilogue\";\n"
"    color:#1D1D1D;\n"
"    border-radius: 10px;\n"
"    border-color: none\n"
"}\n"
"QPushButton:checked {\n"
"    background-color:    #EFEFEF;\n"
"}")
        self.recipe_btn_3.setCheckable(True)
        self.recipe_btn_3.setObjectName("recipe_btn_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 881, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.scan_btn_4.clicked.connect(self.prog_lbl_5.hide) # type: ignore
        self.scan_btn_4.clicked.connect(self.prog_lbl_6.hide) # type: ignore
        self.scan_btn_4.clicked.connect(self.spinBox_2.hide) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.profile_btn_3.setText(_translate("MainWindow", "Profile"))
        self.exercise_btn_3.setText(_translate("MainWindow", "Exercise"))
        self.label.setText(_translate("MainWindow", "NutriFit"))
        self.dashboard_btn_3.setText(_translate("MainWindow", "Dashboard"))
        self.prog_lbl_3.setText(_translate("MainWindow", "Today\'s Progress"))
        self.cal_3.setText(_translate("MainWindow", "Calories"))
        self.prot_3.setText(_translate("MainWindow", "Protein"))
        self.fat_3.setText(_translate("MainWindow", "Fat"))
        self.carb_3.setText(_translate("MainWindow", "Carbs"))
        self.scan_btn_3.setText(_translate("MainWindow", "Scan Food"))
        self.recipe_t_3.setText(_translate("MainWindow", "Recipes"))
        self.label_4.setText(_translate("MainWindow", "Today\'s Meals"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Tab 1"))
        self.search_bar_3.setText(_translate("MainWindow", "Select Ingredients"))
        self.igr_select_3.setText(_translate("MainWindow", "Select Ingredients"))
        self.save_recipe_btn_3.setText(_translate("MainWindow", "Save Recipe "))
        self.new_recipe_btn_3.setText(_translate("MainWindow", "New Recipe"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("MainWindow", "Page"))
        self.prog_lbl_4.setText(_translate("MainWindow", "Breathe"))
        self.prog_lbl_5.setText(_translate("MainWindow", "Breathe in, hold your breath, and breathe out for 4 seconds each"))
        self.prog_lbl_6.setText(_translate("MainWindow", "Set duration of session:"))
        self.scan_btn_4.setText(_translate("MainWindow", "Ready"))
        self.prog_lbl_7.setText(_translate("MainWindow", "inouthold"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_14), _translate("MainWindow", "Page"))
        self.heading_3.setText(_translate("MainWindow", "Your Profile"))
        self.name_3.setText(_translate("MainWindow", "Name"))
        self.age_3.setText(_translate("MainWindow", "Age"))
        self.gender_3.setText(_translate("MainWindow", "Gender"))
        self.line_gender_3.setItemText(0, _translate("MainWindow", "Male"))
        self.line_gender_3.setItemText(1, _translate("MainWindow", "Female"))
        self.line_gender_3.setItemText(2, _translate("MainWindow", "Bakchodi mat kar lode"))
        self.height_3.setText(_translate("MainWindow", "Height (cm)"))
        self.weight_3.setText(_translate("MainWindow", "Weight (kg)"))
        self.goal_weight_3.setText(_translate("MainWindow", "Goal Weight"))
        self.diet_pref_3.setText(_translate("MainWindow", "Dietary Preference"))
        self.line_diet_3.setItemText(0, _translate("MainWindow", "Veg"))
        self.line_diet_3.setItemText(1, _translate("MainWindow", "Non-Veg"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_15), _translate("MainWindow", "Page"))
        self.mediation_btn_3.setText(_translate("MainWindow", "Meditation"))
        self.recipe_btn_3.setText(_translate("MainWindow", "Recipe"))
