# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timer_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(513, 300)
        Form.setStyleSheet("font-size: 30px")
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(30, 70, 71, 51))
        self.lcdNumber.setLineWidth(0)
        self.lcdNumber.setDigitCount(2)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_2.setGeometry(QtCore.QRect(120, 70, 61, 51))
        self.lcdNumber_2.setLineWidth(0)
        self.lcdNumber_2.setDigitCount(2)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_5.setGeometry(QtCore.QRect(200, 70, 61, 51))
        self.lcdNumber_5.setLineWidth(0)
        self.lcdNumber_5.setDigitCount(2)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_3.setGeometry(QtCore.QRect(280, 70, 61, 51))
        self.lcdNumber_3.setLineWidth(0)
        self.lcdNumber_3.setDigitCount(2)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 140, 121, 21))
        self.pushButton.setStyleSheet("QPushButton {\n"
"font: 8pt  \"Epilogue\";\n"
"background-color:rgb(255,255,255)                    \n"
"}\n"
"QPushButton:hover {\n"
"background-color:pink;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 80, 21, 31))
        self.label.setLineWidth(0)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(200, 80, 21, 31))
        self.label_2.setLineWidth(0)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(280, 80, 21, 31))
        self.label_3.setLineWidth(0)
        self.label_3.setIndent(0)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 140, 121, 21))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"font: 8pt  \"Epilogue\";\n"
"background-color:rgb(255,255,255)                    \n"
"}\n"
"QPushButton:hover {\n"
"background-color:pink;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 140, 121, 21))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"font: 8pt  \"Epilogue\";\n"
"background-color:rgb(255,255,255)                    \n"
"}\n"
"QPushButton:hover {\n"
"background-color:pink;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(90, 220, 81, 31))
        self.spinBox.setStyleSheet("QSpinBox {\n"
"    font-family: \"Epilogue\";  \n"
"    font-size: 20pt;\n"
"    background-color: rgb(255,255,255);\n"
"    border-radius:10 pt;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QSpinBox QLineEdit {\n"
"    background-color: rgb(255,255,255);\n"
"    border: none;\n"
"    padding: 4px 6px;\n"
"}\n"
"/*QSpinBox::up-button, QSpinBox::down-button {\n"
"    background-color: rgb(255,255,255);\n"
"    border: 1px solid rgb(200,200,200);\n"
"    border-radius: 3px;\n"
"    min-width: 16px;\n"
"    min-height: 14px;\n"
"}\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover {\n"
"    background-color: pink;\n"
"}*/")
        self.spinBox.setWrapping(False)
        self.spinBox.setFrame(False)
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setReadOnly(False)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox.setSuffix("")
        self.spinBox.setObjectName("spinBox")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(90, 170, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font-size: 20px")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(260, 170, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font-size: 20px")
        self.label_5.setObjectName("label_5")
        self.spinBox_2 = QtWidgets.QSpinBox(Form)
        self.spinBox_2.setGeometry(QtCore.QRect(260, 220, 81, 31))
        self.spinBox_2.setStyleSheet("QSpinBox {\n"
"    font-family: \"Epilogue\";  \n"
"    font-size: 20pt;\n"
"    background-color: rgb(255,255,255);\n"
"    border-radius:10 pt;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QSpinBox QLineEdit {\n"
"    background-color: rgb(255,255,255);\n"
"    border: none;\n"
"    padding: 4px 6px;\n"
"}\n"
"/*QSpinBox::up-button, QSpinBox::down-button {\n"
"    background-color: rgb(255,255,255);\n"
"    border: 1px solid rgb(200,200,200);\n"
"    border-radius: 3px;\n"
"    min-width: 16px;\n"
"    min-height: 14px;\n"
"}\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover {\n"
"    background-color: pink;\n"
"}*/")
        self.spinBox_2.setWrapping(False)
        self.spinBox_2.setFrame(False)
        self.spinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_2.setReadOnly(False)
        self.spinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_2.setSuffix("")
        self.spinBox_2.setObjectName("spinBox_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Start"))
        self.label.setText(_translate("Form", ":"))
        self.label_2.setText(_translate("Form", ":"))
        self.label_3.setText(_translate("Form", "."))
        self.pushButton_2.setText(_translate("Form", "Pause"))
        self.pushButton_3.setText(_translate("Form", "Reset"))
        self.label_4.setText(_translate("Form", "Minutes: "))
        self.label_5.setText(_translate("Form", "Seconds:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
